apiVersion: v1
kind: Service
metadata:
  # Changed to match the Deployment name
  name: iris-classifier-service
spec:
  selector:
    # This MUST match the 'app' label in your Deployment
    app: iris-classifier-service
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8200
  type: LoadBalancer